### ISSUE TITLE
simply support the main feature

### ISSUE THREAD

**Issue by m1ser4ble** [m1ser4ble/JellyfinAutoPlaylist#2]
## TODO 

- [x] execute command using [CliWrap](https://dev.to/tyrrrz/cliwrap-execute-shell-commands-with-extensive-support-for-piping-3gm8)
- [x] Test using python package [billboard charts](https://github.com/guoguo12/billboard-charts?tab=readme-ov-file) 
- [x] ~just make it send http api for missing songs~ execute command for missing songs
