### ISSUE TITLE
support last.fm users

### ISSUE THREAD

**Issue by m1ser4ble** [m1ser4ble/JellyfinAutoPlaylist#8]
## Goal 

* support suggestion playlist for last.fm users
* support auto play for last.fm users

## Task

- [ ] making playlist by using last.fm api for suggestion
- [ ] check if I can make a new item when clicking `...` of a song
- [ ] if I cant, check if I can hook clicking instance mix or get involved in creating instance mix
